---
title: Scientific Publications
excerpt: "A list of my scientific publications"
toc-location: right
---

```{=html}
<link href="../html/pages.css" rel="stylesheet">
```

## Presentations:

*"Efficient Hypersonic Signature Analysis Through Simulation-Based Inference" presented at AIAA SciTech2025.
The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a href="https://arc.aiaa.org/doi/abs/10.2514/6.2025-2157"> Paper </a>
            </div>
```
<iframe src="BayesianWebsite.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 


*"Assessment of Externally Applied Magnetohydrodynamic Effects on the Boundary Layer in Shock-Dominated Hypersonic Flows" presented at AIAA SciTech2025.
The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a href="https://arc.aiaa.org/doi/abs/10.2514/6.2025-2270"> Paper </a>
            </div>
```
<iframe src="SciTech2025MHDWebsite.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 

* "Enhancing Pressure Recovery in a Serpentine Duct using Active Flow Control" presented at APS DFD 2024.
The summary of the proceeding is available here:
```{=html}
            <div class="btn-box">
                <a href="https://meetings.aps.org/Meeting/DFD24/Session/A33.8"> Summary </a>
            </div>
```
<iframe src="APS_DFD24 Website.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 



* "Dynamics of Jet Expansion and Impingement Across a Spectrum of Nozzle Pressure Ratios" presented at AIAA Aviation 2024.
The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a href="https://arc.aiaa.org/doi/abs/10.2514/6.2024-4086"> Paper </a>
            </div>
```
<iframe src="TumukluAviation2024Jetv2Final.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 

* Effect of Spanwise Instabilities on Hypersonic Flows​, presented at AIAA Aviation 2024. The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a href="https://arc.aiaa.org/doi/10.2514/6.2024-3834"> Paper </a>
            </div>
```
<iframe src="DoubleWedgeAviation2024Final.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 

*Laminar Hypersonic Boundary Layer Manipulation via MHD-Leveraging Devices​, presented at AIAA Aviation 2024. The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a href="https://arc.aiaa.org/doi/10.2514/6.2024-4154"> Paper </a>
            </div>
```
<iframe src="AVIATION-2024-HAVA.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 

*Characterization of Hypersonic Instabilities over a Double Cone," presented at AIAA SciTech 2024. The conference proceeding can be found in:
```{=html}
            <div class="btn-box">
                <a> Paper </a>
            </div>
```
<iframe src="Scitech2024_Tumuklu_DoubleCone.pdf" style="width: 800px;height: 480px;border: none;"></iframe> 




